image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # для использования своего скрипта сборки

install:
  # запуск SUT (& означает, что в фоновом режиме - не блокируется терминал для запуска тестов)
  # параметр -P:profile=test активирует тестоввй режим при запуске SUT
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew # предоставление прав на запуск файла gradlew
  # запуск тестов, параметр -Dselenide.headless=true отключает графический интерфейс
  # флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true --info
